// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_mk1UOvzUXy1h5-3v-mqgjyjr8ma4P2s',
    appId: '1:613182012538:web:aa6db2486373ec7b938fc3',
    messagingSenderId: '613182012538',
    projectId: 'splach-413a8',
    authDomain: 'splach-413a8.firebaseapp.com',
    storageBucket: 'splach-413a8.appspot.com',
    measurementId: 'G-QF09Y61VZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWOzcUkKvrvDXP54Xm6PVBqn4xRRS2scc',
    appId: '1:613182012538:android:549e180883514848938fc3',
    messagingSenderId: '613182012538',
    projectId: 'splach-413a8',
    storageBucket: 'splach-413a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu3xGxP8593aDow6gRbj42bny91FJuTfE',
    appId: '1:613182012538:ios:64c353f9fc399018938fc3',
    messagingSenderId: '613182012538',
    projectId: 'splach-413a8',
    storageBucket: 'splach-413a8.appspot.com',
    iosBundleId: 'com.splach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu3xGxP8593aDow6gRbj42bny91FJuTfE',
    appId: '1:613182012538:ios:6f38b52707fb193f938fc3',
    messagingSenderId: '613182012538',
    projectId: 'splach-413a8',
    storageBucket: 'splach-413a8.appspot.com',
    iosBundleId: 'com.splach.RunnerTests',
  );
}
